export type ServiceCategory='maintenance'|'parts'|'mobile'|'crane'|'wash'|'accessories';
export type RequestStatus='submitted'|'waiting'|'offers'|'accepted'|'scheduled'|'in_progress'|'completed'|'cancelled'|'expired';
export interface Customer{id:string;phone:string;name:string;area:string;profileImage?:string;createdAt:string}
export interface Vehicle{id:string;make:string;model:string;year:string;fuel:string;transmission:string;registration?:string;notes?:string;nickname?:string;createdAt:string}
export interface RequestImage{id:string;uri:string}
export interface RequestTimelineEvent{id:string;status:RequestStatus;label:string;createdAt:string}
export interface ServiceRequest{id:string;reference:string;category:ServiceCategory;vehicleId:string;description:string;details:Record<string,string>;images:RequestImage[];status:RequestStatus;createdAt:string;updatedAt:string;timeline:RequestTimelineEvent[];submissionKey:string}
export interface WorkshopReview{id:string;author:string;rating:number;comment:string;createdAt:string}
export interface Workshop{id:string;name:string;initials:string;rating:number;reviewCount:number;area:string;distance:string;description:string;phone:string;whatsapp:string;hours:string;services:ServiceCategory[];warranty:string;gallery:string[];reviews:WorkshopReview[];verified:boolean}
export interface WorkshopOffer{id:string;requestId:string;workshopId:string;priceMin:number;priceMax?:number;availability:string;duration:string;partsIncluded:boolean;warranty:string;message:string;includedWork:string;images:string[];createdAt:string}
export interface AcceptedOffer{id:string;requestId:string;offerId:string;acceptedAt:string}
export interface Rating{id:string;requestId:string;offerId:string;stars:number;comment:string;createdAt:string}
export interface Advertisement{id:string;title:string;subtitle:string;details:string;active:boolean}
export interface ChatMessage{id:string;sender:'customer'|'workshop';text:string;createdAt:string}
export interface ChatConversation{id:string;requestId:string;workshopId:string;messages:ChatMessage[];updatedAt:string}
export type NotificationType='offer'|'reply'|'accepted'|'reminder'|'status';
export interface AppNotification{id:string;type:NotificationType;title:string;body:string;requestId?:string;read:boolean;createdAt:string}
export interface SupportTicket{id:string;number:string;category:string;subject:string;message:string;image?:string;status:'open'|'closed';createdAt:string}
export interface AppSettings{notifications:boolean;sounds:boolean;vibration:boolean;textSize:'small'|'medium'|'large'}
export type RequestDraft=Omit<ServiceRequest,'id'|'reference'|'createdAt'|'updatedAt'|'timeline'|'status'|'submissionKey'>;
export interface AuthState{loggedIn:boolean;verified:boolean;pendingPhone?:string}
export interface DeletionRequest{requestedAt:string;finalizesAt:string}
export interface AppData{version:1;auth:AuthState;customer:null|Customer;vehicles:Vehicle[];requests:ServiceRequest[];offers:WorkshopOffer[];acceptedOffers:AcceptedOffer[];ratings:Rating[];advertisements:Advertisement[];deletionRequest?:DeletionRequest;chats:ChatConversation[];notifications:AppNotification[];tickets:SupportTicket[];settings:AppSettings;demoInitialized:boolean}
